# Generated by Django 5.0.4 on 2024-04-18 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('speciality', models.TextField()),
                ('verified', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.BooleanField()),
                ('experience', models.IntegerField()),
                ('speciality', models.CharField(max_length=200)),
                ('verified', models.BooleanField()),
                ('description', models.TextField()),
                ('medical_facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.medicalfacility')),
            ],
        ),
    ]
