# Generated by Django 5.0.4 on 2024-04-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalfacility',
            name='speciality',
        ),
    ]
