# Generated by Django 5.0.4 on 2024-04-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_medicalfacility_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfacility',
            name='image',
            field=models.TextField(default='https://content.jdmagicbox.com/comp/delhi/30/011pk041630/catalogue/dr-ram-manohar-lohia-hospital-connaught-place-delhi-hospitals-496qb74.jpeg'),
            preserve_default=False,
        ),
    ]
