# Generated by Django 5.0.4 on 2024-04-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_medicalfacility_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofessional',
            name='degrees',
            field=models.TextField(default='https'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalprofessional',
            name='image',
            field=models.TextField(default='MD and MBBS'),
            preserve_default=False,
        ),
    ]
