# Generated by Django 5.0.4 on 2024-04-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_medicalprofessional_degrees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfacility',
            name='short_location',
            field=models.TextField(default='Connaught Place, Delhi'),
            preserve_default=False,
        ),
    ]
